# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      #Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            # fallback to using the latest cache if no exact match exists
            - v1-dependencies-

      - run: yarn install

      - save_cache:
        path:
          - node_modules/
        key: v1-dependencies-{{checksum "package.json"}}

      #run tests
      - run: yarn unit
      - run: yarn build
      # - run: npm publish
