version: 2.1
jobs:
  npm-deploy:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Unit Tests
          command: yarn unit

      - run:
          name: Production build
          command: yarn build

      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$npm_TOKEN
            npm publish

workflows:
  deploy-build:
    jobs:
      - npm-deploy:
          filters:
            branches:
              only:
                - main
