version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:12.13.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run:
          name: Run tests
          command: yarn unit

      - run:
          name: Bundle code
          command: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDT9HZVkO5VYzcMZrbe5ekfSJZbgZlxm9PczsQyJJO8sgHFjHe9nISZMvVXV/gTP7CLm8qWFqGmmlOwxQEaxQrb0DpUykVq/hAUNKGyJjz6GuKWniGJzIfPJq+v/aD+y41CxTkqWRwRqIJxmJ/8U6D5oW1TzAM/cqDBs/40ckF2dja9AvGB4b1OeMPM3msVTe9oV7m5Qh+T6WoejUCpJhendcuwLWbtbzxlF5IOPFzjoYzZhpO4+acWkC0HK/st1jXr7r3X73+RrnUvV2mcKQnGCjt0V8nG2SSAMMv8VU9TPAZ/1GXznMg6V+PD5xRFZIpMXAxCcHpWMfzkr3QjYEg2gKGuArTsQmL/V6Dao39D/0OZW10gZDKK5+1EXcx4gf/pahMwnbF/2NxiFeYpUuqzBwbts/eQMedMUG0ZdeZ3oedHrnrESqmE0tqSVf+9uA6RQdGFS6zihSPmpTC8qunpuE7IVjfHkaN4Lj5nFm8y8+ZjR4zY8S5JOb+IqDmhGSE= sibabale@sibabale"
      - attach_workspace:
          at: ~/repo

      - run:
          name: Git config
          command: |
            git config --global user.email $gitHubEmail
            git config --global user.name $gitHubUsername

      - run:
          name: Release
          command: yarn release &&
            git push --follow-tags origin main
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$npm_TOKEN
            npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              # ignore: /.*/
              only: main
